name: feather
description: A flutter utility library with re-frame esk features
version: 0.0.4
author: AXRS <xander@axrs.io>
homepage: https://github.com/axrs/feather

dependencies:
  flutter:
    sdk: flutter
  flutter_stream_friends: ^0.7.0
  rxdart: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.8.0 <2.0.0"
